### ISSUE TITLE
Vagrant: RunTimeError: could not open display

### ISSUE THREAD

**Issue by WaiTsun-Yeung** [nbcrrolls/txbr-source#3]
I'm not experienced with using virtual machines so any help would be greatly appreciated!

After installing the environment as instructed, I was able to open imod in VirtualBox with a command in terminal, so the basic functionalities should be working.

However, when I was trying to run the code with the test images, this error message appeared: 

```
[vagrant@localhost fhv6]$ sudo runtxbr.py -b fhv6a,fhv6b
Traceback (most recent call last):
  File "/bin/runtxbr.py", line 5, in <module>
    pkg_resources.run_script('TxBR==3.1.4', 'runtxbr.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/runtxbr.py", line 7, in <module>
    import util
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/util/__init__.py", line 12, in <module>
    from improcess import *
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/util/improcess.py", line 3, in <module>
    import pylab
  File "/usr/lib64/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/pylab.py", line 265, in <module>
    from matplotlib.pyplot import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

```

**Comment by coleslaw481** [comment]
Hi,
  I ran other errors myself when trying to launch via vagrant. Turns out `swig*` fails with `yum install` and I had to remove the `*` and psutil.NUM_CPUS was deprecated so I switched to `psutil.cpu_count()`
Once those were fixed and my xwindows was setup I was able to run txbr. The changes have been commited to master branch with this commit: 

https://github.com/nbcrrolls/txbr-source/commit/c04bb6aeb57f2bfdb539e11ae18e53f19ac00784

For the error you are seeing you could try running this on the commandline in your virutalbox instance:

```bash
# Hack to switch matplotlib to use Agg instead of GTKAgg
sed -i 's/GTKAgg/Agg/g' /usr/lib64/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc"
```
The above is taken from commands used to build the singularity image: https://github.com/nbcrrolls/txbr-source/blob/c04bb6aeb57f2bfdb539e11ae18e53f19ac00784/singularity/txbrcentos.def#L54

hope this helps

**Comment by WaiTsun-Yeung** [comment]
That problem I posted went away after I installed the GNOME GUI and Graphical Administration Tools with the guide from this webpage: https://www.itzgeek.com/how-tos/linux/centos-how-tos/install-gnome-gui-on-centos-7-rhel-7.html

Then the psutil.NUM_CPUS error appears. Do I need to download the package and install it fresh to adapt the changes?

Thanks for the help!

**Comment by WaiTsun-Yeung** [comment]
After reinstalling the package I've successfully run the sample script. Thank you for the help!
