### ISSUE TITLE
ImportError: libcfshr.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WaiTsun-Yeung** [nbcrrolls/txbr-source#4]
I have installed the virtual environment on the new computer to run this code and I came across this error:

```
[vagrant@localhost fhv6]$ sudo runtxbr.py -b fhv6a,fhv6b
Traceback (most recent call last):
  File "/bin/runtxbr.py", line 5, in <module>
    pkg_resources.run_script('TxBR==3.1.4', 'runtxbr.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/runtxbr.py", line 10, in <module>
    from txbr import log
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/txbr/__init__.py", line 7, in <module>
    from txbr import *
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/txbr/txbr.py", line 5, in <module>
    import modl
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/modl/__init__.py", line 19, in <module>
    from model import *
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/modl/model.py", line 18, in <module>
    import modfile
ImportError: libcfshr.so: cannot open shared object file: No such file or directory
```

**Comment by coleslaw481** [comment]
It looks like txbr can't find the imod libraries it needs. Did you run these commands before invoking `runtxbr.py`:

```Bash
. /etc/profile.d/modules.sh
module load mpi/openmpi-x86_64
export LD_LIBRARY_PATH=/lib64:/usr/lib64/mpich/lib:/usr/local/IMOD/lib:/usr/local/IMOD/qtlib
```

Above is from this section of documentation:

https://github.com/nbcrrolls/txbr-source/wiki/Using-TXBR-Vagrant-Virtual-machine#step-4-build--install-txbr

**Comment by WaiTsun-Yeung** [comment]
Yes I did. In fact I ran that section of codes one more time just to be sure.

**Comment by coleslaw481** [comment]
hmm, if you do that `sudo` which switches your shell to the `root` user might not carry those environment variables across. 

If you do want to run as root try running `sudo -u root /bin/bash` then issue those commands to setup the environment:

https://github.com/nbcrrolls/txbr-source/wiki/Using-TXBR-Vagrant-Virtual-machine#step-4-build--install-txbr
