### ISSUE TITLE
Error: All series should have the same number of objects!

### ISSUE THREAD

**Issue by WaiTsun-Yeung** [nbcrrolls/txbr-source#5]
Hi! We have been using your algorithm on a 4-tilt series (by imaging 1a and 1c together first then rotating the sample by 45 degrees to image 1b and 1d). However the following error message popped up. The algorithm ran successfully however when only 1a and 1c were run together. Could you explain what does it mean and how can we fix it?

Thank you for your time. And hope you are well.

grant@localhost 4_tilt_test]$ runtxbr.py -b 1a,1b,1c,1d
INFO: txbr_align.py -b 1a,1b,1c,1d -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1
INFO: Load project: (b='1a,1b,1c,1d',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Initialize TxBR project: (/home/vagrant/Desktop/4_tilt_test,1) ['a', 'b', 'c', 'd']
INFO: Project bin factor set to: 1
INFO: Load Reconstruction from /home/vagrant/Desktop/4_tilt_test/1.txbr
INFO: Reconstruction loaded for series /home/vagrant/Desktop/4_tilt_test/1.txbr...
INFO: Load series: (b='1a',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Set the bin factor of txbr.utilities.datastack.MRCStack: /home/vagrant/Desktop/4_tilt_test/1a.preali, bin=1 to 1
INFO: Load tilt angles for series <txbr.txbr.TxBRSerie: basename='1a', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'>.
INFO: 75 tilt angles loaded for 1a... from its stack
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1a.txbr.bin1.
INFO: Projection Map loaded for /home/vagrant/Desktop/4_tilt_test/1a.txbr.bin1...
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1a.trj.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1a.trj!
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1a', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Rescale series 1a to reconstruction <txbr.txbr.Reconstruction: 1 x:[-309.0,2540.0] y:[-337.0,2484.0] z:[-77.0,78.0]  scale:[11.3,11.3,11.3]>
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1a', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Series '1a' has been added
INFO: Load series: (b='1b',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Set the bin factor of txbr.utilities.datastack.MRCStack: /home/vagrant/Desktop/4_tilt_test/1b.preali, bin=1 to 1
INFO: Load tilt angles for series <txbr.txbr.TxBRSerie: basename='1b', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'>.
INFO: 81 tilt angles loaded for 1b... from its stack
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1b.txbr.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1b.txbr!
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1b.trj.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1b.trj!
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1b', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Rescale series 1b to reconstruction <txbr.txbr.Reconstruction: 1 x:[-309.0,2540.0] y:[-337.0,2484.0] z:[-77.0,78.0]  scale:[11.3,11.3,11.3]>
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1b', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Series '1b' has been added
INFO: Load series: (b='1c',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Set the bin factor of txbr.utilities.datastack.MRCStack: /home/vagrant/Desktop/4_tilt_test/1c.preali, bin=1 to 1
INFO: Load tilt angles for series <txbr.txbr.TxBRSerie: basename='1c', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'>.
INFO: 81 tilt angles loaded for 1c... from its stack
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1c.txbr.bin1.
INFO: Projection Map loaded for /home/vagrant/Desktop/4_tilt_test/1c.txbr.bin1...
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1c.trj.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1c.trj!
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1c', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Rescale series 1c to reconstruction <txbr.txbr.Reconstruction: 1 x:[-309.0,2540.0] y:[-337.0,2484.0] z:[-77.0,78.0]  scale:[11.3,11.3,11.3]>
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1c', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Series '1c' has been added
INFO: Load series: (b='1d',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Set the bin factor of txbr.utilities.datastack.MRCStack: /home/vagrant/Desktop/4_tilt_test/1d.preali, bin=1 to 1
INFO: Load tilt angles for series <txbr.txbr.TxBRSerie: basename='1d', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'>.
INFO: 81 tilt angles loaded for 1d... from its stack
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1d.txbr.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1d.txbr!
INFO: Loading map from /home/vagrant/Desktop/4_tilt_test/1d.trj.
WARNING: Unable to load maps from /home/vagrant/Desktop/4_tilt_test/1d.trj!
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1d', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Rescale series 1d to reconstruction <txbr.txbr.Reconstruction: 1 x:[-309.0,2540.0] y:[-337.0,2484.0] z:[-77.0,78.0]  scale:[11.3,11.3,11.3]>
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1d', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Series '1d' has been added
INFO: Project bin factor set to: 1
INFO: Initialize Alignment object
INFO: Validate Project
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1a', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1b', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1c', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Validate the series <txbr.txbr.TxBRSerie: basename='1d', dir='/home/vagrant/Desktop/4_tilt_test', wd='/home/vagrant/Desktop/4_tilt_test'> against its metadata
INFO: (stack<->metadata)  sx: 11.33<->11.33    sy: 11.33<->11.33
INFO: Beam Model: General, Order 1, Multiple, t-fixed [False,False,False]
INFO: Order (0,1,0,0)
INFO: Full Minimization: False
INFO: Reference Axis: [-0.09,-1.00,-0.01]
INFO: Reference Axis: [0.00,1.00,0.00]
INFO: Reference Axis: [0.09,1.00,0.02]
INFO: Reference Axis: [0.00,1.00,0.00]
Traceback (most recent call last):
  File "/usr/bin/txbr_align.py", line 5, in <module>
    pkg_resources.run_script('TxBR==3.1.4', 'txbr_align.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_align.py", line 241, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_align.py", line 228, in main
    alignment = contalign.TxBRContourAlign( project, **keywords )
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/txbr/align/contalign.py", line 268, in __init__
    self.initialize()
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/txbr/align/contalign.py", line 347, in initialize
    raise ValueError, "All series should have the same number of objects!"
ValueError: All series should have the same number of objects!
An error happened for command: txbr_align.py -b 1a,1b,1c,1d -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1

**Comment by coleslaw481** [comment]
The error message at the end mentions the number of objects is not the same in all the series. I could be totally wrong here, but I suspect this is referring to the fiducial marker list which must have the same objects in all series. https://github.com/nbcrrolls/txbr-source#usage

**Comment by WaiTsun-Yeung** [comment]
Hi, we've tried to adjust for that and a new error message appears: too many indices

Here's the full error message: 

[vagrant@localhost 4_tilt_test]$ runtxbr.py -b. 1a,1b,1c,1d
INFO: txbr_align.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1
INFO: Load project: (b='.',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Initialize TxBR project: (/home/vagrant/Desktop/4_tilt_test,.) ['']
INFO: Project bin factor set to: 1
INFO: Initialize Alignment object
INFO: Validate Project
INFO: Beam Model: General, Order 1, Multiple, t-fixed [False,False,False]
INFO: Order (0,1,0,0)
INFO: Full Minimization: False
INFO: Order: n1=1   n2=1   n3=1   n4=0
INFO: Fixed Variables: a=False   b=True   c=True   d=False
INFO: Symbolic Calculation of the Core Cost functions, its derivatives and hessians.
INFO: Number of core variables: a=9 b=8 c=4 d=1
INFO: Number of free variables: n=10
INFO: Final core error expression calculated.
INFO: Number of core variables: a=9 b=8 c=4 d=1
INFO: error = a_2_2**2*d_0**2*b_0_3**2+a_1_1*b_1_2*a_2_0*b_1_3-c_0_1*a_0_0*b_0_1+(2. ...
INFO: Total number of monoms in the core cost function: 156
INFO: Polify the Error functions...
INFO: Extension to Multiple tilts and patches.
INFO: Theoretical total number of free variables: 0.
INFO: Calculated Total number of free variables (a+b+d): 0/0. [a=0,b=0,c=0,d=0]
INFO: Global Calculations of Error, its derivatives and hessians
INFO: Do initial estimates!
WARNING: No Series to process!
INFO: txbr_filter.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1 --fine --doClean
WARNING: Check the sign for the filtering angle
INFO: Load project: (b='.',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Initialize TxBR project: (/home/vagrant/Desktop/4_tilt_test,.) ['']
INFO: Project bin factor set to: 1
INFO: Filter procedure: MPI-rank=0  MPI-size:1
INFO: Finalize filters
Traceback (most recent call last):
  File "/usr/bin/txbr_filter.py", line 5, in <module>
    pkg_resources.run_script('TxBR==3.1.4', 'txbr_filter.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 253, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 248, in main
    __finalize_mpi_filter__( project, bin=fine and bin or None, doClean=doClean )
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 158, in __finalize_mpi_filter__
    mrc.newstack( inputs, output, bin=bin, clean=doClean )
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/mrc/mrcutil.py", line 59, in newstack
    nx = numpy.mean(dims[:,0]/bin).astype('int')
IndexError: too many indices
An error happened for command: txbr_filter.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1 --fine --doClean
[vagrant@localhost 4_tilt_test]$ runtxbr.py -b. 1a,1b,1c,1d
INFO: txbr_align.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1
INFO: Load project: (b='.',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Initialize TxBR project: (/home/vagrant/Desktop/4_tilt_test,.) ['']
INFO: Project bin factor set to: 1
INFO: Initialize Alignment object
INFO: Validate Project
INFO: Beam Model: General, Order 1, Multiple, t-fixed [False,False,False]
INFO: Order (0,1,0,0)
INFO: Full Minimization: False
INFO: Order: n1=1   n2=1   n3=1   n4=0
INFO: Fixed Variables: a=False   b=True   c=True   d=False
INFO: Symbolic Calculation of the Core Cost functions, its derivatives and hessians.
INFO: Number of core variables: a=9 b=8 c=4 d=1
INFO: Number of free variables: n=10
INFO: Final core error expression calculated.
INFO: Number of core variables: a=9 b=8 c=4 d=1
INFO: error = (2.0)*b_0_2**2*a_1_2*d_0*a_1_0+b_1_1*d_0*a_0_2*b_1_2*a_1_1+b_1_2**2*a_ ...
INFO: Total number of monoms in the core cost function: 156
INFO: Polify the Error functions...
INFO: Extension to Multiple tilts and patches.
INFO: Theoretical total number of free variables: 0.
INFO: Calculated Total number of free variables (a+b+d): 0/0. [a=0,b=0,c=0,d=0]
INFO: Global Calculations of Error, its derivatives and hessians
INFO: Do initial estimates!
WARNING: No Series to process!
INFO: txbr_filter.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1 --fine --doClean
WARNING: Check the sign for the filtering angle
INFO: Load project: (b='.',d='/home/vagrant/Desktop/4_tilt_test',bin='1')
INFO: Initialize TxBR project: (/home/vagrant/Desktop/4_tilt_test,.) ['']
INFO: Project bin factor set to: 1
INFO: Filter procedure: MPI-rank=0  MPI-size:1
INFO: Finalize filters
Traceback (most recent call last):
  File "/usr/bin/txbr_filter.py", line 5, in <module>
    pkg_resources.run_script('TxBR==3.1.4', 'txbr_filter.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 253, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 248, in main
    __finalize_mpi_filter__( project, bin=fine and bin or None, doClean=doClean )
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/txbr_filter.py", line 158, in __finalize_mpi_filter__
    mrc.newstack( inputs, output, bin=bin, clean=doClean )
  File "/usr/lib64/python2.7/site-packages/TxBR-3.1.4-py2.7-linux-x86_64.egg/mrc/mrcutil.py", line 59, in newstack
    nx = numpy.mean(dims[:,0]/bin).astype('int')
IndexError: too many indices
An error happened for command: txbr_filter.py -b . -d /home/vagrant/Desktop/4_tilt_test --wd /home/vagrant/Desktop/4_tilt_test --bin 1 --fine --doClean
